language: java
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: b9397c3c-845f-4e2d-b280-ec1dcfc5497d
  app: rachaconta-se
  on:
    repo: gian418/rachaconta